# Generated by Django 3.0.7 on 2020-06-30 13:33

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
